/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "unit_test.check" instead.
 */

#include <check.h>

#include "s21_matrix.h"

// S21_CREATE_MATRIX //

START_TEST(create_matrix_1) {
  matrix_t res = {0};
  int return_code = s21_create_matrix(0, 0, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(create_matrix_2) {
  matrix_t res = {0};
  int return_code = s21_create_matrix(1, 0, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(create_matrix_3) {
  matrix_t res = {0};
  int return_code = s21_create_matrix(1, 1, &res);
  ck_assert_int_eq(return_code, OK);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(create_matrix_4) {
  matrix_t res = {0};
  int return_code = s21_create_matrix(5, 1, &res);
  ck_assert_int_eq(return_code, OK);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(create_matrix_5) {
  matrix_t res = {0};
  int return_code = s21_create_matrix(5, 7, &res);
  ck_assert_int_eq(return_code, OK);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(create_matrix_6) {
  matrix_t res = {0};
  int return_code = s21_create_matrix(3, -2, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(create_matrix_7) {
  matrix_t *res = NULL;
  int return_code = s21_create_matrix(3, 2, res);
  ck_assert_int_eq(return_code, INCORRECT);

  // S21_REMOVE_MATRIX
}
END_TEST

START_TEST(remove_matrix_1) {
  matrix_t res = {0};
  s21_create_matrix(5, 4, &res);
  s21_remove_matrix(&res);
  ck_assert_int_eq(res.rows, 0);
  ck_assert_int_eq(res.columns, 0);
  ck_assert_ptr_eq(res.matrix, NULL);

  // S21_EQ_MATRIX
}
END_TEST

START_TEST(eq_matrix_1) {
  matrix_t A = {0};
  matrix_t B = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &B);
  double k = 1.0;
  double g = 2.5;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = g;
    }
  }
  int return_code = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(return_code, FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(eq_matrix_2) {
  matrix_t A = {0};
  matrix_t B = {0};
  s21_create_matrix(4, 5, &A);
  s21_create_matrix(3, 3, &B);
  double k = 1.0;
  double g = 2.5;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = g;
    }
  }
  int return_code = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(return_code, FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(eq_matrix_3) {
  matrix_t A = {0};
  matrix_t B = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &B);
  double g = 2.5;
  double k = 2.5;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = g;
      g++;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = k;
      k++;
    }
  }
  int return_code = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(return_code, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(eq_matrix_4) {
  matrix_t A = {0};
  matrix_t B = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &B);
  double k = 1.0;
  double g = 1.0;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = g;
      g++;
    }
  }
  int return_code = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(return_code, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(eq_matrix_5) {
  matrix_t A = {0};
  matrix_t B = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &B);
  double k = 1.0000000;
  double g = 1.0000001;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = g;
      g++;
    }
  }
  int return_code = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(return_code, FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(eq_matrix_6) {
  matrix_t A = {0};
  matrix_t B = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &B);
  double k = 1.0000000;
  double g = 1.00000001;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = g;
      g++;
    }
  }
  int return_code = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(return_code, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);

  // S21_SUM_MATRIX //
}
END_TEST

START_TEST(sum_matrix_1) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &B);
  s21_create_matrix(3, 3, &correct);
  double k = 1.0;
  double g = 2.5;
  double f = 3.5;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = g;
    }
  }
  for (int i = 0; i < correct.rows; i++) {
    for (int j = 0; j < correct.columns; j++) {
      correct.matrix[i][j] = f;
      f++;
    }
  }
  int return_code = s21_sum_matrix(&A, &B, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(sum_matrix_2) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &B);
  s21_create_matrix(3, 3, &correct);
  double k = 1.0;
  double g = 2.5;
  double f = 3.5;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = g;
      g++;
    }
  }
  for (int i = 0; i < correct.rows; i++) {
    for (int j = 0; j < correct.columns; j++) {
      correct.matrix[i][j] = f;
      f += 2;
    }
  }
  int return_code = s21_sum_matrix(&A, &B, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(sum_matrix_3) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  s21_create_matrix(2, 2, &A);
  s21_create_matrix(3, 3, &B);
  int return_code = s21_sum_matrix(&A, &B, &res);
  ck_assert_int_eq(return_code, ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(sum_matrix_4) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  s21_create_matrix(0, 2, &A);
  s21_create_matrix(3, 3, &B);
  int return_code = s21_sum_matrix(&A, &B, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(sum_matrix_5) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t *res = NULL;
  s21_create_matrix(0, 2, &A);
  s21_create_matrix(3, 3, &B);
  int return_code = s21_sum_matrix(&A, &B, res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(sum_matrix_6) {
  matrix_t *A = NULL;
  matrix_t B = {0};
  matrix_t res = {0};
  s21_create_matrix(0, 2, A);
  s21_create_matrix(3, 3, &B);
  int return_code = s21_sum_matrix(A, &B, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);

  // S21_SUB_MATRIX //
}
END_TEST

START_TEST(sub_matrix_1) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &B);
  s21_create_matrix(3, 3, &correct);
  double k = 2.5;
  double g = 1.3;
  double f = 1.2;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = g;
    }
  }
  for (int i = 0; i < correct.rows; i++) {
    for (int j = 0; j < correct.columns; j++) {
      correct.matrix[i][j] = f;
      f++;
    }
  }
  int return_code = s21_sub_matrix(&A, &B, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(sub_matrix_2) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(2, 2, &B);
  int return_code = s21_sub_matrix(&A, &B, &res);
  ck_assert_int_eq(return_code, ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(sub_matrix_3) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(0, 2, &B);
  int return_code = s21_sub_matrix(&A, &B, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(sub_matrix_4) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &B);
  s21_create_matrix(3, 3, &correct);
  double k = 2.5;
  double g = 1.3;
  double f = 1.2000000;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = g;
      g++;
    }
  }
  for (int i = 0; i < correct.rows; i++) {
    for (int j = 0; j < correct.columns; j++) {
      correct.matrix[i][j] = f;
    }
  }
  int return_code = s21_sub_matrix(&A, &B, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(sub_matrix_5) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &B);
  s21_create_matrix(3, 3, &correct);
  double k = 2.5;
  double g = 1.3;
  double f = 1.2000001;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = g;
      g++;
    }
  }
  for (int i = 0; i < correct.rows; i++) {
    for (int j = 0; j < correct.columns; j++) {
      correct.matrix[i][j] = f;
    }
  }
  int return_code = s21_sub_matrix(&A, &B, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(sub_matrix_6) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t *res = NULL;
  s21_create_matrix(0, 2, &A);
  s21_create_matrix(3, 3, &B);
  int return_code = s21_sub_matrix(&A, &B, res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(sub_matrix_7) {
  matrix_t *A = NULL;
  matrix_t B = {0};
  matrix_t res = {0};
  s21_create_matrix(0, 2, A);
  s21_create_matrix(3, 3, &B);
  int return_code = s21_sub_matrix(A, &B, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);

  // S21_MULT_NUMBER //
}
END_TEST

START_TEST(mult_number_1) {
  matrix_t A = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &correct);
  double k = 2.5;
  double f = 3.25;
  double value = 1.3;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < correct.rows; i++) {
    for (int j = 0; j < correct.columns; j++) {
      correct.matrix[i][j] = f;
      f += 1.3;
    }
  }
  int return_code = s21_mult_number(&A, value, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(mult_number_2) {
  matrix_t A = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &correct);
  double k = 2.5134512;
  double f = 3.2674866;
  double value = 1.3;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < correct.rows; i++) {
    for (int j = 0; j < correct.columns; j++) {
      correct.matrix[i][j] = f;
      f += 1.3;
    }
  }
  int return_code = s21_mult_number(&A, value, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(mult_number_3) {
  matrix_t A = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &correct);
  double k = 2.5134512;
  double f = 3.2674866;
  double value = 1.3;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < correct.rows; i++) {
    for (int j = 0; j < correct.columns; j++) {
      correct.matrix[i][j] = f;
      f += 1.3;
    }
  }
  int return_code = s21_mult_number(&A, value, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(mult_number_4) {
  matrix_t A = {0};
  matrix_t res = {0};
  s21_create_matrix(0, 3, &A);
  double value = 1.3;
  int return_code = s21_mult_number(&A, value, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(mult_number_5) {
  matrix_t A = {0};
  matrix_t res = {0};
  s21_create_matrix(0, 3, &A);
  double value = NAN;
  int return_code = s21_mult_number(&A, value, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(mult_number_6) {
  matrix_t A = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &correct);
  double k = 2.5134512;
  double f = -5.9229478;
  double value = -2.3565;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < correct.rows; i++) {
    for (int j = 0; j < correct.columns; j++) {
      correct.matrix[i][j] = f;
      f -= 2.3565;
    }
  }
  int return_code = s21_mult_number(&A, value, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(mult_number_7) {
  matrix_t A = {0};
  matrix_t *res = NULL;
  s21_create_matrix(3, 3, &A);
  double value = 0;
  int return_code = s21_mult_number(&A, value, res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(mult_number_8) {
  matrix_t *A = NULL;
  matrix_t res = {0};
  s21_create_matrix(3, 3, A);
  double value = 0;
  int return_code = s21_mult_number(A, value, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&res);

  // S21_MULT_MATRIX //
}
END_TEST

START_TEST(mult_matrix_1) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(4, 5, &B);
  int return_code = s21_mult_matrix(&A, &B, &res);
  ck_assert_int_eq(return_code, ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(mult_matrix_2) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &B);
  s21_create_matrix(3, 3, &correct);
  double k = 2.5;
  double g = 1.3;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = g;
      g++;
    }
  }
  correct.matrix[0][0] = 51.1500000;
  correct.matrix[0][1] = 61.6500000;
  correct.matrix[0][2] = 72.1500000;
  correct.matrix[1][0] = 89.8500000;
  correct.matrix[1][1] = 109.3500000;
  correct.matrix[1][2] = 128.8500000;
  correct.matrix[2][0] = 128.5500000;
  correct.matrix[2][1] = 157.0500000;
  correct.matrix[2][2] = 185.5500000;
  int return_code = s21_mult_matrix(&A, &B, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(mult_matrix_3) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(3, 2, &A);
  s21_create_matrix(2, 4, &B);
  s21_create_matrix(3, 4, &correct);
  double k = 2.5;
  double g = 1.3;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < B.rows; i++) {
    for (int j = 0; j < B.columns; j++) {
      B.matrix[i][j] = g;
      g++;
    }
  }
  correct.matrix[0][0] = 21.8000000;
  correct.matrix[0][1] = 27.8000000;
  correct.matrix[0][2] = 33.8000000;
  correct.matrix[0][3] = 39.8000000;
  correct.matrix[1][0] = 35.0000000;
  correct.matrix[1][1] = 45.0000000;
  correct.matrix[1][2] = 55.0000000;
  correct.matrix[1][3] = 65.0000000;
  correct.matrix[2][0] = 48.2000000;
  correct.matrix[2][1] = 62.2000000;
  correct.matrix[2][2] = 76.2000000;
  correct.matrix[2][3] = 90.2000000;
  int return_code = s21_mult_matrix(&A, &B, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(mult_matrix_4) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  s21_create_matrix(2, 3, &A);
  s21_create_matrix(2, 2, &B);
  int return_code = s21_mult_matrix(&A, &B, &res);
  ck_assert_int_eq(return_code, ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(mult_matrix_5) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t res = {0};
  s21_create_matrix(0, 3, &A);
  s21_create_matrix(2, 2, &B);
  int return_code = s21_mult_matrix(&A, &B, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(mult_matrix_6) {
  matrix_t A = {0};
  matrix_t *B = NULL;
  matrix_t res = {0};
  s21_create_matrix(0, 3, &A);
  s21_create_matrix(2, 2, B);
  int return_code = s21_mult_matrix(&A, B, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(mult_matrix_7) {
  matrix_t A = {0};
  matrix_t B = {0};
  matrix_t *res = NULL;
  s21_create_matrix(0, 3, &A);
  s21_create_matrix(2, 2, &B);
  int return_code = s21_mult_matrix(&A, &B, res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);

  // S21_TRANSPOSE //
}
END_TEST

START_TEST(transpose_1) {
  matrix_t A = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(2, 3, &A);
  s21_create_matrix(3, 2, &correct);
  double k = 2.5;
  double f = 2.5;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < correct.columns; i++) {
    for (int j = 0; j < correct.rows; j++) {
      correct.matrix[j][i] = f;
      f++;
    }
  }
  int return_code = s21_transpose(&A, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(transpose_2) {
  matrix_t A = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(2, 2, &A);
  s21_create_matrix(2, 2, &correct);
  double k = 2.5;
  double f = 2.5;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < correct.columns; i++) {
    for (int j = 0; j < correct.rows; j++) {
      correct.matrix[j][i] = f;
      f++;
    }
  }
  int return_code = s21_transpose(&A, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(transpose_3) {
  matrix_t A = {0};
  matrix_t res = {0};
  s21_create_matrix(2, -2, &A);
  int return_code = s21_transpose(&A, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(transpose_4) {
  matrix_t A = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(1, 1, &A);
  s21_create_matrix(1, 1, &correct);
  double k = 2.5;
  double f = 2.5;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  for (int i = 0; i < correct.columns; i++) {
    for (int j = 0; j < correct.rows; j++) {
      correct.matrix[j][i] = f;
      f++;
    }
  }
  int return_code = s21_transpose(&A, &res);
  ck_assert_int_eq(return_code, OK);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(transpose_5) {
  matrix_t A = {0};
  matrix_t *res = NULL;
  s21_create_matrix(1, 1, &A);
  int return_code = s21_transpose(&A, res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(transpose_6) {
  matrix_t *A = NULL;
  matrix_t res = {0};
  s21_create_matrix(1, 1, A);
  int return_code = s21_transpose(A, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&res);

  // S21_DETERMINANT //
}
END_TEST

START_TEST(determinant_1) {
  matrix_t A = {0};
  double res = 0;
  double correct = 0;
  s21_create_matrix(3, 3, &A);
  double k = 2.5;
  for (int i = 0; i < A.rows; i++) {
    for (int j = 0; j < A.columns; j++) {
      A.matrix[i][j] = k;
      k++;
    }
  }
  int return_code = s21_determinant(&A, &res);
  ck_assert_int_eq(return_code, OK);
  ck_assert_double_eq(res, correct);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(determinant_2) {
  matrix_t A = {0};
  double res = 0;
  double correct = -60;
  s21_create_matrix(4, 4, &A);
  A.matrix[0][0] = 5;
  A.matrix[0][1] = 8;
  A.matrix[0][2] = 0;
  A.matrix[0][3] = -4;
  A.matrix[1][0] = 0;
  A.matrix[1][1] = 1;
  A.matrix[1][2] = 10;
  A.matrix[1][3] = 1;
  A.matrix[2][0] = 0;
  A.matrix[2][1] = 0;
  A.matrix[2][2] = -4;
  A.matrix[2][3] = 0;
  A.matrix[3][0] = 0;
  A.matrix[3][1] = 0;
  A.matrix[3][2] = 0;
  A.matrix[3][3] = 3;
  int return_code = s21_determinant(&A, &res);
  ck_assert_int_eq(return_code, OK);
  ck_assert_double_eq(res, correct);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(determinant_3) {
  matrix_t A = {0};
  double res = 0;
  double correct = 204;
  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = -2;
  A.matrix[0][2] = 3;
  A.matrix[1][0] = 4;
  A.matrix[1][1] = 0;
  A.matrix[1][2] = 6;
  A.matrix[2][0] = -7;
  A.matrix[2][1] = 8;
  A.matrix[2][2] = 9;
  int return_code = s21_determinant(&A, &res);
  ck_assert_int_eq(return_code, OK);
  ck_assert_double_eq(res, correct);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(determinant_4) {
  matrix_t A = {0};
  double res = 0;
  double correct = 85.656;
  s21_create_matrix(1, 1, &A);
  A.matrix[0][0] = 85.656;
  int return_code = s21_determinant(&A, &res);
  ck_assert_int_eq(return_code, OK);
  ck_assert_double_eq(res, correct);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(determinant_5) {
  matrix_t A = {0};
  double res = 0;
  s21_create_matrix(1, 2, &A);
  int return_code = s21_determinant(&A, &res);
  ck_assert_int_eq(return_code, ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(determinant_6) {
  matrix_t A = {0};
  double res = 0;
  s21_create_matrix(2, 0, &A);
  int return_code = s21_determinant(&A, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(determinant_7) {
  matrix_t A = {0};
  double res = 0;
  double correct = 0;
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 2;
  A.matrix[1][0] = 1;
  A.matrix[1][1] = 2;
  int return_code = s21_determinant(&A, &res);
  ck_assert_int_eq(return_code, OK);
  ck_assert_double_eq(res, correct);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(determinant_8) {
  matrix_t A = {0};
  double *res = NULL;
  s21_create_matrix(2, 2, &A);
  int return_code = s21_determinant(&A, res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(determinant_9) {
  matrix_t *A = NULL;
  double res = 0;
  s21_create_matrix(2, 2, A);
  int return_code = s21_determinant(A, &res);
  ck_assert_int_eq(return_code, INCORRECT);

  // S21_CALC_COMPLEMENTS //
}
END_TEST

START_TEST(calc_complements_1) {
  matrix_t A = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &correct);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = -2;
  A.matrix[0][2] = 3;
  A.matrix[1][0] = 4;
  A.matrix[1][1] = 0;
  A.matrix[1][2] = 6;
  A.matrix[2][0] = -7;
  A.matrix[2][1] = 8;
  A.matrix[2][2] = 9;

  correct.matrix[0][0] = -48;
  correct.matrix[0][1] = -78;
  correct.matrix[0][2] = 32;
  correct.matrix[1][0] = 42;
  correct.matrix[1][1] = 30;
  correct.matrix[1][2] = 6;
  correct.matrix[2][0] = -12;
  correct.matrix[2][1] = 6;
  correct.matrix[2][2] = 8;
  int return_code = s21_calc_complements(&A, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(calc_complements_2) {
  matrix_t A = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(4, 4, &A);
  s21_create_matrix(4, 4, &correct);
  A.matrix[0][0] = 5;
  A.matrix[0][1] = 8;
  A.matrix[0][2] = 0;
  A.matrix[0][3] = -4;
  A.matrix[1][0] = 0;
  A.matrix[1][1] = 1;
  A.matrix[1][2] = 10;
  A.matrix[1][3] = 1;
  A.matrix[2][0] = 0;
  A.matrix[2][1] = 0;
  A.matrix[2][2] = -4;
  A.matrix[2][3] = 0;
  A.matrix[3][0] = 0;
  A.matrix[3][1] = 0;
  A.matrix[3][2] = 0;
  A.matrix[3][3] = 3;

  correct.matrix[0][0] = -12;
  correct.matrix[0][1] = -0;
  correct.matrix[0][2] = 0;
  correct.matrix[0][3] = -0;
  correct.matrix[1][0] = 96;
  correct.matrix[1][1] = -60;
  correct.matrix[1][2] = -0;
  correct.matrix[1][3] = 0;
  correct.matrix[2][0] = 240;
  correct.matrix[2][1] = -150;
  correct.matrix[2][2] = 15;
  correct.matrix[2][3] = -0;
  correct.matrix[3][0] = -48;
  correct.matrix[3][1] = 20;
  correct.matrix[3][2] = -0;
  correct.matrix[3][3] = -20;
  int return_code = s21_calc_complements(&A, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(calc_complements_3) {
  matrix_t A = {0};
  matrix_t res = {0};
  s21_create_matrix(4, 3, &A);
  int return_code = s21_calc_complements(&A, &res);
  ck_assert_int_eq(return_code, ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(calc_complements_4) {
  matrix_t A = {0};
  matrix_t res = {0};
  s21_create_matrix(4, 0, &A);
  int return_code = s21_calc_complements(&A, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(calc_complements_5) {
  matrix_t A = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(1, 1, &A);
  s21_create_matrix(1, 1, &correct);
  A.matrix[0][0] = -48;
  correct.matrix[0][0] = -48;
  int return_code = s21_calc_complements(&A, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(calc_complements_6) {
  matrix_t A = {0};
  matrix_t *res = NULL;
  s21_create_matrix(1, 1, &A);
  int return_code = s21_calc_complements(&A, res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(calc_complements_7) {
  matrix_t *A = NULL;
  matrix_t res = {0};
  s21_create_matrix(2, 2, A);
  int return_code = s21_calc_complements(A, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&res);

  // S21_INVERSE_MATRIX //
}
END_TEST

START_TEST(inverse_matrix_1) {
  matrix_t A = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(3, 3, &A);
  s21_create_matrix(3, 3, &correct);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = -2;
  A.matrix[0][2] = 3;
  A.matrix[1][0] = 4;
  A.matrix[1][1] = 0;
  A.matrix[1][2] = 6;
  A.matrix[2][0] = -7;
  A.matrix[2][1] = 8;
  A.matrix[2][2] = 9;

  correct.matrix[0][0] = -0.2352941;
  correct.matrix[0][1] = 0.2058824;
  correct.matrix[0][2] = -0.0588235;
  correct.matrix[1][0] = -0.3823529;
  correct.matrix[1][1] = 0.1470588;
  correct.matrix[1][2] = 0.0294118;
  correct.matrix[2][0] = 0.1568627;
  correct.matrix[2][1] = 0.0294118;
  correct.matrix[2][2] = 0.0392157;
  int return_code = s21_inverse_matrix(&A, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(inverse_matrix_2) {
  matrix_t A = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(4, 4, &A);
  s21_create_matrix(4, 4, &correct);
  A.matrix[0][0] = 5;
  A.matrix[0][1] = 8;
  A.matrix[0][2] = 0;
  A.matrix[0][3] = -4;
  A.matrix[1][0] = 0;
  A.matrix[1][1] = 1;
  A.matrix[1][2] = 10;
  A.matrix[1][3] = 1;
  A.matrix[2][0] = 0;
  A.matrix[2][1] = 0;
  A.matrix[2][2] = -4;
  A.matrix[2][3] = 0;
  A.matrix[3][0] = 0;
  A.matrix[3][1] = 0;
  A.matrix[3][2] = 0;
  A.matrix[3][3] = 3;

  correct.matrix[0][0] = 0.2;
  correct.matrix[0][1] = -1.6;
  correct.matrix[0][2] = -4;
  correct.matrix[0][3] = 0.8;
  correct.matrix[1][0] = 0;
  correct.matrix[1][1] = 1;
  correct.matrix[1][2] = 2.5;
  correct.matrix[1][3] = -0.3333333;
  correct.matrix[2][0] = 0;
  correct.matrix[2][1] = 0;
  correct.matrix[2][2] = -0.25;
  correct.matrix[2][3] = 0;
  correct.matrix[3][0] = 0;
  correct.matrix[3][1] = 0;
  correct.matrix[3][2] = 0;
  correct.matrix[3][3] = 0.3333333;
  int return_code = s21_inverse_matrix(&A, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(inverse_matrix_3) {
  matrix_t A = {0};
  matrix_t res = {0};
  s21_create_matrix(4, 3, &A);
  int return_code = s21_inverse_matrix(&A, &res);
  ck_assert_int_eq(return_code, ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(inverse_matrix_4) {
  matrix_t A = {0};
  matrix_t res = {0};
  s21_create_matrix(4, 0, &A);
  int return_code = s21_inverse_matrix(&A, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(inverse_matrix_5) {
  matrix_t A = {0};
  matrix_t res = {0};
  matrix_t correct = {0};
  s21_create_matrix(1, 1, &A);
  s21_create_matrix(1, 1, &correct);
  A.matrix[0][0] = 48;
  correct.matrix[0][0] = 0.0208333;
  int return_code = s21_inverse_matrix(&A, &res);
  int equal = s21_eq_matrix(&res, &correct);
  ck_assert_int_eq(return_code, OK);
  ck_assert_int_eq(equal, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
  s21_remove_matrix(&correct);
}
END_TEST

START_TEST(inverse_matrix_6) {
  matrix_t A = {0};
  matrix_t res = {0};
  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 1;
  A.matrix[0][1] = 2;
  A.matrix[1][0] = 1;
  A.matrix[1][1] = 2;
  int return_code = s21_inverse_matrix(&A, &res);
  ck_assert_int_eq(return_code, ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&res);
}
END_TEST

START_TEST(inverse_matrix_7) {
  matrix_t A = {0};
  matrix_t *res = NULL;
  s21_create_matrix(2, 2, &A);
  int return_code = s21_inverse_matrix(&A, res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(inverse_matrix_8) {
  matrix_t *A = NULL;
  matrix_t res = {0};
  s21_create_matrix(2, 2, A);
  int return_code = s21_inverse_matrix(A, &res);
  ck_assert_int_eq(return_code, INCORRECT);
  s21_remove_matrix(&res);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, create_matrix_1);
  tcase_add_test(tc1_1, create_matrix_2);
  tcase_add_test(tc1_1, create_matrix_3);
  tcase_add_test(tc1_1, create_matrix_4);
  tcase_add_test(tc1_1, create_matrix_5);
  tcase_add_test(tc1_1, create_matrix_6);
  tcase_add_test(tc1_1, create_matrix_7);
  tcase_add_test(tc1_1, remove_matrix_1);
  tcase_add_test(tc1_1, eq_matrix_1);
  tcase_add_test(tc1_1, eq_matrix_2);
  tcase_add_test(tc1_1, eq_matrix_3);
  tcase_add_test(tc1_1, eq_matrix_4);
  tcase_add_test(tc1_1, eq_matrix_5);
  tcase_add_test(tc1_1, eq_matrix_6);
  tcase_add_test(tc1_1, sum_matrix_1);
  tcase_add_test(tc1_1, sum_matrix_2);
  tcase_add_test(tc1_1, sum_matrix_3);
  tcase_add_test(tc1_1, sum_matrix_4);
  tcase_add_test(tc1_1, sum_matrix_5);
  tcase_add_test(tc1_1, sum_matrix_6);
  tcase_add_test(tc1_1, sub_matrix_1);
  tcase_add_test(tc1_1, sub_matrix_2);
  tcase_add_test(tc1_1, sub_matrix_3);
  tcase_add_test(tc1_1, sub_matrix_4);
  tcase_add_test(tc1_1, sub_matrix_5);
  tcase_add_test(tc1_1, sub_matrix_6);
  tcase_add_test(tc1_1, sub_matrix_7);
  tcase_add_test(tc1_1, mult_number_1);
  tcase_add_test(tc1_1, mult_number_2);
  tcase_add_test(tc1_1, mult_number_3);
  tcase_add_test(tc1_1, mult_number_4);
  tcase_add_test(tc1_1, mult_number_5);
  tcase_add_test(tc1_1, mult_number_6);
  tcase_add_test(tc1_1, mult_number_7);
  tcase_add_test(tc1_1, mult_number_8);
  tcase_add_test(tc1_1, mult_matrix_1);
  tcase_add_test(tc1_1, mult_matrix_2);
  tcase_add_test(tc1_1, mult_matrix_3);
  tcase_add_test(tc1_1, mult_matrix_4);
  tcase_add_test(tc1_1, mult_matrix_5);
  tcase_add_test(tc1_1, mult_matrix_6);
  tcase_add_test(tc1_1, mult_matrix_7);
  tcase_add_test(tc1_1, transpose_1);
  tcase_add_test(tc1_1, transpose_2);
  tcase_add_test(tc1_1, transpose_3);
  tcase_add_test(tc1_1, transpose_4);
  tcase_add_test(tc1_1, transpose_5);
  tcase_add_test(tc1_1, transpose_6);
  tcase_add_test(tc1_1, determinant_1);
  tcase_add_test(tc1_1, determinant_2);
  tcase_add_test(tc1_1, determinant_3);
  tcase_add_test(tc1_1, determinant_4);
  tcase_add_test(tc1_1, determinant_5);
  tcase_add_test(tc1_1, determinant_6);
  tcase_add_test(tc1_1, determinant_7);
  tcase_add_test(tc1_1, determinant_8);
  tcase_add_test(tc1_1, determinant_9);
  tcase_add_test(tc1_1, calc_complements_1);
  tcase_add_test(tc1_1, calc_complements_2);
  tcase_add_test(tc1_1, calc_complements_3);
  tcase_add_test(tc1_1, calc_complements_4);
  tcase_add_test(tc1_1, calc_complements_5);
  tcase_add_test(tc1_1, calc_complements_6);
  tcase_add_test(tc1_1, calc_complements_7);
  tcase_add_test(tc1_1, inverse_matrix_1);
  tcase_add_test(tc1_1, inverse_matrix_2);
  tcase_add_test(tc1_1, inverse_matrix_3);
  tcase_add_test(tc1_1, inverse_matrix_4);
  tcase_add_test(tc1_1, inverse_matrix_5);
  tcase_add_test(tc1_1, inverse_matrix_6);
  tcase_add_test(tc1_1, inverse_matrix_7);
  tcase_add_test(tc1_1, inverse_matrix_8);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
